on: [ push ]

jobs:
  javascript:
    runs-on: ubuntu-latest
    name: javascript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/javascript/
        with:
          who-to-greet: 'Mona the Octocat'
      # `hello` ステップからの出力を使用する
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  docker:
    runs-on: ubuntu-latest
    name: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/actions/docker/
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # 「hello」ステップの出力を使用する
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  composite:
    runs-on: ubuntu-latest
    name: composite
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/composite/
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash